/* autogenerate the 200 possible overloads
function f() {
    let result = "";
    let _ = "";
    let n = ",1";
    for (let i = 2; i < 200; i++) {
        result += `#define TRANSFORM_${i}(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_${i - 1}(NAME_, TUPLE_TAIL ARGS_)` + "\n";
        n = "," + i + n;
        _ = ",_" + i + _;
    }
    console.log(result);
    console.log(_);
    console.log(n);
}
*/

// some pins like F7 conflict
#define KC_FN1 KC_F1
#define KC_FN2 KC_F2
#define KC_FN3 KC_F3
#define KC_FN4 KC_F4
#define KC_FN5 KC_F5
#define KC_FN6 KC_F6
#define KC_FN7 KC_F7
#define KC_FN8 KC_F8
#define KC_FN9 KC_F9
#define KC_FN10 KC_F10
#define KC_FN11 KC_F11
#define KC_FN12 KC_F12
#define KC_FN13 KC_F13
#define KC_FN14 KC_F14
#define KC_FN15 KC_F15
#define KC_FN16 KC_F16
#define KC_FN17 KC_F17
#define KC_FN18 KC_F18
#define KC_FN19 KC_F19
#define KC_FN20 KC_F20
#define KC_FN21 KC_F21
#define KC_FN22 KC_F22
#define KC_FN23 KC_F23
#define KC_FN24 KC_F24


#define EVAL(...) __VA_ARGS__
#define VARCOUNT(...) \
   EVAL(VARCOUNT_I(__VA_ARGS__,199,198,197,196,195,194,193,192,191,190,189,188,187,186,185,184,183,182,181,180,179,178,177,176,175,174,173,172,171,170,169,168,167,166,165,164,163,162,161,160,159,158,157,156,155,154,153,152,151,150,149,148,147,146,145,144,143,142,141,140,139,138,137,136,135,134,133,132,131,130,129,128,127,126,125,124,123,122,121,120,119,118,117,116,115,114,113,112,111,110,109,108,107,106,105,104,103,102,101,100,99,98,97,96,95,94,93,92,91,90,89,88,87,86,85,84,83,82,81,80,79,78,77,76,75,74,73,72,71,70,69,68,67,66,65,64,63,62,61,60,59,58,57,56,55,54,53,52,51,50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,))
#define VARCOUNT_I(_,_199,_198,_197,_196,_195,_194,_193,_192,_191,_190,_189,_188,_187,_186,_185,_184,_183,_182,_181,_180,_179,_178,_177,_176,_175,_174,_173,_172,_171,_170,_169,_168,_167,_166,_165,_164,_163,_162,_161,_160,_159,_158,_157,_156,_155,_154,_153,_152,_151,_150,_149,_148,_147,_146,_145,_144,_143,_142,_141,_140,_139,_138,_137,_136,_135,_134,_133,_132,_131,_130,_129,_128,_127,_126,_125,_124,_123,_122,_121,_120,_119,_118,_117,_116,_115,_114,_113,_112,_111,_110,_109,_108,_107,_106,_105,_104,_103,_102,_101,_100,_99,_98,_97,_96,_95,_94,_93,_92,_91,_90,_89,_88,_87,_86,_85,_84,_83,_82,_81,_80,_79,_78,_77,_76,_75,_74,_73,_72,_71,_70,_69,_68,_67,_66,_65,_64,_63,_62,_61,_60,_59,_58,_57,_56,_55,_54,_53,_52,_51,_50,_49,_48,_47,_46,_45,_44,_43,_42,_41,_40,_39,_38,_37,_36,_35,_34,_33,_32,_31,_30,_29,_28,_27,_26,_25,_24,_23,_22,_21,_20,_19,_18,_17,_16,_15,_14,_13,_12,_11,_10,_9,_8,_7,_6,_5,_4,_3,_2,X_,...) X_
#define GLUE(X,Y) GLUE_I(X,Y)
#define GLUE_I(X,Y) X##Y
#define FIRST(...) EVAL(FIRST_I(__VA_ARGS__,))
#define FIRST_I(X,...) X
#define TUPLE_TAIL(...) EVAL(TUPLE_TAIL_I(__VA_ARGS__))
#define TUPLE_TAIL_I(X,...) (__VA_ARGS__)

#define TRANSFORM(NAME_, ARGS_) (GLUE(TRANSFORM_,VARCOUNT ARGS_)(NAME_, ARGS_))
#define TRANSFORM_1(NAME_, ARGS_) NAME_ ARGS_

#define TRANSFORM_2(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_1(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_3(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_2(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_4(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_3(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_5(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_4(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_6(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_5(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_7(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_6(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_8(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_7(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_9(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_8(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_10(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_9(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_11(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_10(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_12(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_11(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_13(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_12(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_14(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_13(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_15(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_14(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_16(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_15(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_17(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_16(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_18(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_17(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_19(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_18(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_20(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_19(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_21(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_20(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_22(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_21(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_23(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_22(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_24(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_23(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_25(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_24(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_26(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_25(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_27(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_26(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_28(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_27(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_29(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_28(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_30(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_29(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_31(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_30(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_32(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_31(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_33(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_32(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_34(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_33(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_35(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_34(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_36(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_35(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_37(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_36(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_38(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_37(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_39(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_38(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_40(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_39(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_41(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_40(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_42(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_41(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_43(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_42(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_44(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_43(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_45(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_44(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_46(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_45(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_47(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_46(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_48(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_47(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_49(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_48(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_50(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_49(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_51(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_50(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_52(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_51(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_53(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_52(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_54(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_53(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_55(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_54(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_56(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_55(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_57(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_56(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_58(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_57(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_59(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_58(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_60(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_59(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_61(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_60(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_62(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_61(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_63(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_62(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_64(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_63(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_65(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_64(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_66(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_65(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_67(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_66(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_68(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_67(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_69(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_68(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_70(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_69(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_71(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_70(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_72(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_71(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_73(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_72(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_74(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_73(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_75(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_74(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_76(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_75(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_77(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_76(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_78(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_77(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_79(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_78(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_80(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_79(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_81(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_80(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_82(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_81(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_83(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_82(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_84(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_83(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_85(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_84(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_86(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_85(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_87(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_86(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_88(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_87(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_89(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_88(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_90(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_89(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_91(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_90(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_92(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_91(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_93(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_92(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_94(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_93(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_95(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_94(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_96(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_95(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_97(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_96(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_98(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_97(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_99(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_98(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_100(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_99(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_101(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_100(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_102(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_101(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_103(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_102(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_104(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_103(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_105(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_104(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_106(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_105(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_107(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_106(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_108(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_107(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_109(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_108(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_110(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_109(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_111(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_110(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_112(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_111(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_113(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_112(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_114(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_113(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_115(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_114(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_116(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_115(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_117(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_116(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_118(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_117(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_119(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_118(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_120(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_119(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_121(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_120(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_122(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_121(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_123(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_122(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_124(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_123(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_125(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_124(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_126(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_125(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_127(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_126(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_128(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_127(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_129(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_128(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_130(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_129(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_131(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_130(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_132(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_131(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_133(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_132(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_134(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_133(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_135(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_134(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_136(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_135(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_137(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_136(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_138(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_137(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_139(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_138(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_140(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_139(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_141(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_140(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_142(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_141(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_143(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_142(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_144(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_143(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_145(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_144(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_146(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_145(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_147(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_146(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_148(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_147(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_149(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_148(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_150(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_149(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_151(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_150(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_152(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_151(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_153(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_152(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_154(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_153(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_155(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_154(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_156(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_155(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_157(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_156(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_158(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_157(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_159(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_158(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_160(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_159(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_161(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_160(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_162(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_161(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_163(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_162(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_164(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_163(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_165(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_164(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_166(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_165(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_167(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_166(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_168(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_167(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_169(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_168(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_170(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_169(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_171(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_170(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_172(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_171(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_173(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_172(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_174(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_173(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_175(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_174(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_176(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_175(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_177(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_176(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_178(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_177(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_179(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_178(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_180(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_179(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_181(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_180(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_182(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_181(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_183(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_182(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_184(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_183(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_185(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_184(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_186(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_185(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_187(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_186(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_188(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_187(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_189(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_188(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_190(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_189(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_191(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_190(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_192(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_191(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_193(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_192(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_194(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_193(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_195(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_194(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_196(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_195(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_197(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_196(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_198(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_197(NAME_, TUPLE_TAIL ARGS_)
#define TRANSFORM_199(NAME_, ARGS_) NAME_(FIRST ARGS_), TRANSFORM_198(NAME_, TUPLE_TAIL ARGS_)

#define _PREPEND_KC(X) GLUE(KC_, X)
#define KC__(x) x
#define MAKE_INITIALIZER(...) LA(__VA_ARGS__)
#define LAYOUT_PREPEND_KC(...) \
   EVAL(MAKE_INITIALIZER TRANSFORM(_PREPEND_KC, (__VA_ARGS__)))
