name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "pypy3"]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        #token: ${{ secrets.PAT_TOKEN }}
    - uses: "actions/setup-python@v2"
      with:
        python-version: "${{ matrix.python-version }}"
    - name: setup qmk
      run: qmk setup -H qmk_firmware
    - name: make
      run: make
